# Generated by Django 6.0.1 on 2026-01-31 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medicines", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="distributor",
            field=models.ForeignKey(
                limit_choices_to={"role": "distributor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
